name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Java
        run: sudo apt-get install -y default-jre  

      - name: Download PlantUML JAR
        run: wget https://github.com/plantuml/plantuml/releases/download/v1.2025.2/plantuml-1.2025.2.jar

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget graphviz
  
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen
      
      - name: Create output directory
        run: mkdir -p docs_output/ru/
      
      - name: Create .nojekyll file
        run: |
          mkdir -p docs_output/ru/html
          touch docs_output/ru/html/.nojekyll

      - name: Check folder structure
        run: ls -la