name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

env:
  DOXYGEN_OUTPUT: docs_output/ru
  PLANTUML_JAR: plantuml-1.2025.2.jar    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Java
        run: sudo apt-get install -y default-jre  

      - name: Download PlantUML JAR
        run: wget https://github.com/plantuml/plantuml/releases/download/v1.2025.2/${{ env.PLANTUML_JAR }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget graphviz
  
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen
      
      - name: Create output directory
        run: mkdir -p ${{ env.DOXYGEN_OUTPUT }}
      
      - name: Create .nojekyll file
        run: |
          mkdir -p ${{ env.DOXYGEN_OUTPUT }}/html
          touch ${{ env.DOXYGEN_OUTPUT }}/html/.nojekyll

      - name: Check folder structure
        run: ls -la
      
      - name: Generate Doxygen documentation
        run: doxygen config_gh
        env:
          OUTPUT_DIR_ENV: ${{ env.DOXYGEN_OUTPUT }}
          PLANTUML_JAR_PATH_ENV: ${{ env.PLANTUML_JAR }}
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.GH_DOCS }}
          branch: gh-pages
          folder: ${{ env.DOXYGEN_OUTPUT }}/html
          clean: true
          force: true