name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download PlantUML JAR
        run: |
          wget https://github.com/plantuml/plantuml/releases/download/v1.2025.2/plantuml-1.2025.2.jar -O /home/runner/plantuml-1.2025.2.jar

      - name: Create output directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Creating docs_output/ru directory..."
          mkdir -p /home/runner/work/${{ github.repository }}/docs_output/ru
          echo "Directory contents after creation:"
          ls -la /home/runner/work/${{ github.repository }}/docs_output/
          echo "Contents of docs_output/ru:"
          ls -la /home/runner/work/${{ github.repository }}/docs_output/ru/

      - name: Run Doxygen with PlantUML
        uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs_output/ru/html
          config_file: ./config_gh
          doxygen_version: 1.9.8
        env:
          PLANTUML_JAR_PATH_ENV: /home/runner/plantuml-1.2025.2.jar
          OUTPUT_DIR_ENV: /home/runner/work/${{ github.repository }}/docs_output/ru/